config/routes.rb
Rails.application.routes.draw do
  default_url_options host: 'usagle.com'
  devise_for :users
  resources :categories
  resources :items, only: %i[index show new create]

  namespace :admin do
    resources :items
  end

  root 'items#index'

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items
  validates :name, presence: true

  extend FriendlyId
  friendly_id :name, use: :slugged
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :category

  validates :title, :description, presence: true
  validates :title, length: { maximum: 50 }
  validates :description, length: { maximum: 3000 }
  validates :price, numericality: { greater_than: 0 }

  has_attached_file :image, styles: { large: '900x400>', medium: '253x150>', thumb: '150x150#' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  extend FriendlyId
  friendly_id :title, use: :slugged

  enum status: { wait_moderation: 0, approved: 1, declined: 2 }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :confirmable, :validatable

  has_many :item
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :check_admin

  layout 'admin'

  protected

  def check_admin
    redirect_to root_path, alert: 'Access is denied! You are not authorized to access this page' unless current_user.admin?
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < Admin::BaseController
  before_action :find_item, only: %i[show edit update destroy]
  before_action :find_categories
  before_action :find_statuses, only: %i[new create]

  def index
    @items = Item
    @items = @items.where(status: :approved)
    order = params[:order] == 'asc' ? 'asc' : 'desc'
    @items = @items.order("created_at #{order}")
  end

  def show; end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.item.new(item_params)
    if @item.save
      redirect_to admin_items_path, success: 'Item successfully created'
    else
      flash.now[:danger] = 'Item not created'
      render :new
    end
  end

  def edit
    @statuses = Item.statuses
  end

  def update
    @statuses = Item.statuses
    if @item.update(item_params)
      redirect_to admin_items_path, success: 'Item successfully updated'
    else
      flash.now[:danger] = 'Item not updated'
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to admin_items_path, success: 'Item successfully deleted'
  end

  private

  def find_categories
    @categories = Category.all
  end

  def find_item
    @item = Item.friendly.find(params[:id])
  end

  def find_statuses
    @statuses = Item.all.statuses
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :current_user, :slug, :image, :category_id, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  add_flash_types :success, :danger, :info, :warning
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!, except: %i[show]
  before_action :find_category, only: %i[show edit update destroy]
  before_action :find_categories

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params

    if @category.save
      redirect_to categories_path, success: 'Your category was successfully saved!'
    else
      flash.now[:danger] = 'I was unable to save your category.'
      render :new
    end
  end

  def show
    @items = Item.where(category_id: [@category], status: [:approved])
  end

  def edit; end

  def update
    if @category.update category_params
      redirect_to categories_path, success: 'Your category was successfully saved!'
    else
      flash.now[:danger] = 'I was unable to update your category.'
      render :edit
    end
  end

  def destroy
    @category.destroy
    redirect_to categories_path, success: 'Your category was successfully deleted!'
  end

  private

  def category_params
    params.require(:category).permit(:name, :slug)
  end

  def find_category
    @category = Category.friendly.find(params[:id])
  end

  def find_categories
    @categories = Category.all
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :find_item, only: %i[show edit update destroy]
  before_action :find_categories

  def index
    @items = Item
    @items = @items.where(status: :approved)
    order = params[:order] == 'asc' ? 'asc' : 'desc'
    @items = @items.order("created_at #{order}")
  end

  def show; end

  def new
    @item = Item.new
  end

  def create
    @item = current_user.item.new(item_params)
    if @item.save
      redirect_to items_path, success: 'Item successfully created'
    else
      flash.now[:danger] = 'Item not created'
      render :new
    end
  end

  def edit
    @statuses = Item.statuses
  end

  def update
    @statuses = Item.statuses
    if @item.update(item_params)
      redirect_to @item, success: 'Item successfully updated'
    else
      flash.now[:danger] = 'Item not updated'
      render :edit
    end
  end

  def destroy
    @item.destroy
    redirect_to items_path, success: 'Item successfully deleted'
  end

  private

  def find_categories
    @categories = Category.all
  end

  def find_item
    @item = Item.friendly.find(params[:id])
  end

  def item_params
    params.require(:item).permit(:title, :description, :price, :current_user, :slug, :image, :category_id, :status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(name)
    { success: 'alert-success',
      error:  'alert-danger',
      danger: 'alert-danger',
      alert:  'alert-warning',
      notice: 'alert-info' }[name.to_sym] || name
  end

  def full_title(page_title = '')
    base_title = 'Usagle. The new age marketplace'
    if page_title.empty?
      base_title
    else
      page_title + ' | ' + base_title
    end
  end
end

app/views/admin/items/_form.html.erb
<%= render 'common/errors', resource: @item %>

<%= form_for [:admin, @item], html: { multipart: true  } do |f| %>

  <div class="form-group">
    <%= f.label :title, class: "exampleInputEmail1" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 6, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true  },  class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(@statuses.collect { |s| [s[0].humanize, s[0]]  }, selected: @item.status), {} , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "#{ @item.new_record? ? 'Create' : 'Edit' }", class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/admin/items/_item.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100">
    <%= link_to image_tag(item.image.url(:medium), class: 'card-img-top'), item_path(item) if item.image? %>
    <div class="card-body">
      <h4 class="card-title">
        <%= link_to item.title, admin_item_path(item) %>
      </h4>
      <h5>$ <%= item.price %></h5>
      <p class="card-text">
        <%= truncate(strip_tags(item.description),length: 80) %>
      </p>
    </div>
    <div class="card-footer">
      <small>
        <time><%= item.created_at.to_date.strftime("%d %B, %Y") %></time>
        <% if user_signed_in? %>
          |
          <%= link_to 'Show', admin_item_path(item) %>
          |
          <%= link_to 'Edit', edit_admin_item_path(item) %>
          |
          <%= link_to 'Destroy', [:admin, item], method: :delete, data: { confirm: 'Are you sure ?'  } %>
        <% else %>
          |
          <%= link_to item.category.name, item.category %>
        <% end %>
      </small>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<%= render 'shared/submenu' %>

<div class="col-lg-9">
  <div class="card mt-4">
  <%= image_tag @item.image.url(:large, class: 'card-img-top img-fluid') if @item.image? %>
</div>

<div class="card-outline-secondary my-4">
  <h3 class="text-center">Edit an ad</h3>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/admin/items/index.html.erb
<% provide(:title, "Control Panel") %> 
<%= render 'shared/submenu' %>

<div class="col-lg-9">
  <%= render 'shared/slide' %>
    <div class="row">
      <%= render @items %>
    </div>
</div>

app/views/admin/items/new.html.erb
<%= render 'shared/submenu' %>

<div class="col-lg-9">
  <div class="card-outline-secondary my-4">
    <h3 class="text-center">New an ad</h3>
    <div class="card-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<%= render 'shared/submenu' %>

<div class="col-lg-9">
  <div class="card mt-4">
    <%= image_tag @item.image.url(:large, class: 'card-img-top img-fluid') if @item.image? %>
    <div class="card-body">
      <h3 class="card-title"><%= @item.title %></h3>
      <strong class="status"><%= @item.status.humanize %></strong>
      <h4>$ <%= @item.price %></h4>
      <p class="card-text"><%= @item.description.html_safe %></p>
      <% if @item.user.present? %>
          <p>Added: <%= @item.user.email %></p>
      <% end %>
    </div>
  </div>
  <div class="card card-outline-secondary my-4">
    <div class="card-header">
      To write a message(responsible for several hours): <button type="button" class="btn btn-info">Write message</button>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<%= render 'common/errors', resource: @category %>

<%= form_for @category do |f| %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit t('.submit', action: @category.new_record? ? t('common.create') : t('common.edit')), class: 'btn btn-primary' %>
  </div>

  <br>

<% end %>

app/views/categories/edit.html.erb
<%= render 'shared/submenu' %>

<div class="col-lg-9">
  <div class="mt-4">
</div>

<div class="card-outline-secondary my-4">
  <h3 class="text-center"><%= t('.title') %></h3>
  <div class="card-body">
    <%= render 'form' %>
  </div>
</div>
</div>

app/views/categories/index.html.erb
<% provide(:title, "Category") %>
<%= render 'shared/submenu' %>

<div class="col-lg-9">
  <div class="row">
    <section id="categories">
      <table class="table">
        <thead>
          <tr>
            <th>#</th>
            <th>Name</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each_with_index do |category, index| %>
            <tr>
              <td><%= index + 1 %></td>
              <td><%= category.name %></td>
              <td>
                <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-primary btn-sm'  %>
                <%= link_to 'Destroy', category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm'  %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </section>
  </div>
</div>

app/views/categories/new.html.erb
<%= render 'shared/submenu' %>

<div class="col-lg-9">
  <div class="card-outline-secondary my-4">
    <h3 class="text-center"><%= t('.title') %></h3>
    <div class="card-body">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<%= render 'shared/submenu' %>
<% provide(:title, "Categories") %>

<div class="col-lg-9">
  <%= render 'shared/slide' %>
  <div class="row">
    <% if @category.items.empty?  %>
      <h2>No items in it category</h2>
    <% else %>
      <%= render @items %>
    <% end %>
  </div>
</div>

app/views/common/_errors.html.erb
<% if resource.errors.any? %>
  <div class="alert alert-danger">
    <h5><%= t('common.errors') %></h5>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/items/_form.html.erb
<%= render 'common/errors', resource: @item %>

<%= form_for @item, html: { multipart: true  } do |f| %>

  <div class="form-group">
    <%= f.label :title, class: "exampleInputEmail1" %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: 6, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.order(:name), :id, :name, { include_blank: true  },  class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "#{ @item.new_record? ? 'Create' : 'Edit' }", class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/items/_item.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100">
    <%= link_to image_tag(item.image.url(:medium), class: 'card-img-top'), item_path(item) if item.image? %>
    <div class="card-body">
      <h4 class="card-title">
        <%= link_to item.title, item_path(item) %>
      </h4>
      <h5>$ <%= item.price %></h5>
      <p class="card-text">
        <%= truncate(strip_tags(item.description),length: 80) %>
      </p>
    </div>
    <div class="card-footer">
      <small>
        <time><%= item.created_at.to_date.strftime("%d %B, %Y") %></time>
        |
        <%= link_to item.category.name, item.category %>
      </small>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<%= render 'shared/submenu' %>

<div class="col-lg-9">
  <div class="card mt-4">
    <%= image_tag @item.image.url(:large, class: 'card-img-top img-fluid') if @item.image? %>
    <div class="card-body">
      <h3 class="card-title"><%= @item.title %></h3>
      <strong class="status"><%= @item.status.humanize %></strong>
      <h4>$ <%= @item.price %></h4>
      <p class="card-text"><%= @item.description.html_safe %></p>
    </div>
  </div>
  <div class="card card-outline-secondary my-4">
    <div class="card-header">
      To write a message(responsible for several hours): <button type="button" class="btn btn-info">Write message</button>
    </div>
  </div>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |name, message| %>
  <div class="alert <%= bootstrap_class_for(name) %>">
    <button class="close" data-dismiss="alert">&times;</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
 <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Usagle.com 2018</p>
      </div>
      <!-- /.container -->
    </footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <%= link_to "Usagle", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="<%= root_path %>">Home
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= items_path %>">Catalog</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Help</a>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
          <%= link_to "Place an ad", new_item_path, class: 'btn btn-outline-light pull-xs-right' %>
          <li class="nav-item account">
            <% if user_signed_in? %>
              <a class="nav-link">Account: <%= current_user.email %></a>
            <% end %>
          </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_rails_default.erb
<%= csrf_meta_tags %>
<%= stylesheet_link_tag    'application', media: 'all',
                                          'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_scripts.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.1/js/bootstrap.bundle.min.js"></script>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>

  <head>

    <%= render 'layouts/rails_default' %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <%= favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/png' %>

    <title><%= full_title(yield(:title)) %></title>

  </head>

  <body class='<%= controller.controller_name %>'>

    <%= render 'layouts/flash' %>
    <%= render 'layouts/nav' %>

    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>

    <%= render 'layouts/scripts' %>

  </body>

</html>

app/views/layouts/application.html.slim
doctype html
html

  head

    = render 'layouts/rails_default'
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"
    meta name="description" content=""
    = favicon_link_tag asset_path('favicon.ico'), :rel => 'icon', :type =>  'image/png'

    title = full_title(yield(:title))

  head

  body class='= controller.controller_name'

    = render 'layouts/flash'
    = render 'layouts/nav'

    div class="container"
      div class="row"
        = yield

    = render 'layouts/footer'

    = render 'layouts/scripts'

app/views/shared/_slide.html.erb
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item active">
      <%= image_tag("http://www.guengl.eu/images/made/uploads/news-images/378534-apple-logo-wallpaper_900_350_70_c1_c_t_0_-50.jpg", class: 'd-block img-fluid') %>
    </div>
    <div class="carousel-item">
      <%= image_tag("https://www.casasbahia-imagens.com.br/html/conteudo-produto/2031/3987823/imagens/ipad-mini-3-apple-3g-4g-wifi-douradol-ios8-fino-leve-potente-7.9polegadas-2cameras-64bits.jpg", class: 'd-block img-fluid') %>
    </div>
    <div class="carousel-item">
      <%= image_tag("https://www.benaturalorganics.com/v/vspfiles/assets/images/pomme3.jpg", class: 'd-block img-fluid') %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/shared/_submenu.html.erb
<div class="col-lg-3">
  <h1 class="my-4">Categories</h1>
  <div class="list-group">
    <% @categories.each do |category| %>
      <a href="#"><%= link_to category.name, category, class: "list-group-item" %></a>
  <% end %>
  </div>
  <h1 class="my-4">Sorting by</h1>
  <p>
    <i class="fa fa-sort-amount-desc" aria-hidden="true"></i>
      <%= link_to "New on top", items_path(order: "desc") %>
    <i class="fa fa-sort-amount-asc" aria-hidden="true"></i>
      <%= link_to "Old on top", items_path(order: "asc") %>
  </p>
</div>